#! /bin/bash

#АВТОСТАРТ
sxhkd &
numlockx &
nitrogen --restore &
~/.config/polybar/launch.sh
picom &
xsetroot -cursor_name left_ptr &
firefox &
#telegram-desktop &
#steam-native &
#discord &


#ВОРКСПЕЙСЫ
bspc monitor -d            

#РАМКИ И ГАПСЫ
bspc config border_width         1
bspc config window_gap          10

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"

#ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНАЫ
bspc config presel_feedback_color "fd2e59"

#ПРИ ПОМОЩИ ЭТОЙ ХРЕНИ МОЖНО СДЕЛАТЬ ГАПСЫ ТОЛЬКО МЕЖДУ ОКНАМИ
#bspc config window_gap $gap;
#bspc config top_padding -$(($gap+2))
#bspc config left_padding -$(($gap+2))
#bspc config right_padding -$(($gap+4))
#bspc config bottom_padding $(($PANEL_HEIGHT-$gap))

#КОФИЦИЕНТ РАЗДЕЛЕНИЯ, СКОЛЬКО ПРОЦЕНТОВ ОСТАНЕТСЯ ОТ РОДИТЕЛЬСКОГО ОКНА ПРИ ОТКРЫТИИ НОВОГО
bspc config split_ratio          0.5

#ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

#РЕЖИМ МОНОКЛЯ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config single_monocle	     false

#ОТКЛЮЧЕНИЕ ГАПСОВ РАМОК И ОТСТУПОВ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

#СХЕМЫ СОГЛАСНО КОТОРЫМ БУДУТ ОТКРЫВАТСЯ ОКНА
#bspc config automatic_scheme	spiral

#ПРАВИЛА ОКОН
bspc rule -a Firefox state=floating rectangle=1350x900+50+90 desktop='^1'
bspc rule -a TelegramDesktop state=floating follow=off desktop='^1'
#bspc rule -a ghostwriter state=floating follow=off
bspc rule -a discord state=floating rectangle=820x900+1050+90 follow=off 
#bspc rule -a TelegramDesktop state=floating follow=off rectangle=420x900+1450+90 desktop='^1'
bspc rule -a steam state=fullscreen follow=off desktop='^6' 
# bspc rule -a Lutris state=floating follow=off rectangle=1200x700+360+190 desktop='^6' 
# bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
#bspc rule -a dmenu rectangle=900x22+610+90
#bspc rule -a Media viewer rectangle=1350x900+285+90 state=floating
# bspc rule -a Inkscape desktop='^3'
# bspc rule -a Blender desktop='^2'
